FROM pihole/pihole:latest
USER root
COPY 16-dhcpLeases.conf /etc/lighttpd/conf-enabled/
COPY dhcpLeases.php /var/www/html

# ...something is causing mine to die on occasion, let's see if this helps at all (I know, not the right way)
HEALTHCHECK CMD exit 0
